//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUOsaber.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DUOsaber.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap _170Y1_1 {
            get {
                object obj = ResourceManager.GetObject("_170Y1_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap _170Y1_2 {
            get {
                object obj = ResourceManager.GetObject("_170Y1_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap _300y1_1 {
            get {
                object obj = ResourceManager.GetObject("_300y1_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap _300y1_2 {
            get {
                object obj = ResourceManager.GetObject("_300y1_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Always Center Start과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string alwaysCenter {
            get {
                return ResourceManager.GetString("alwaysCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pointer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string audience {
            get {
                return ResourceManager.GetString("audience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   block과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string block {
            get {
                return ResourceManager.GetString("block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap btn_icon_exclamation_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("btn_icon_exclamation_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Change master과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string changePresenter {
            get {
                return ResourceManager.GetString("changePresenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check device matching과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string checkForDeviceMatching {
            get {
                return ResourceManager.GetString("checkForDeviceMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap chois_logo {
            get {
                object obj = ResourceManager.GetObject("chois_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap chois_logo1 {
            get {
                object obj = ResourceManager.GetObject("chois_logo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Clip_path_group {
            get {
                object obj = ResourceManager.GetObject("Clip_path_group", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Please check the connection by pressing the button.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CMtex3 {
            get {
                return ResourceManager.GetString("CMtex3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Press the button shown in the picture for 2 seconds과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CMtext1_1 {
            get {
                return ResourceManager.GetString("CMtext1-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When the LED flashes, press the Next button.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CMtext1_2 {
            get {
                return ResourceManager.GetString("CMtext1-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection in progress.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CMtext2_1 {
            get {
                return ResourceManager.GetString("CMtext2-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When the LED stops flashing, press the Next button.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CMtext2_2 {
            get {
                return ResourceManager.GetString("CMtext2-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string colorChange {
            get {
                return ResourceManager.GetString("colorChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string colorPointer {
            get {
                return ResourceManager.GetString("colorPointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string connectionFailed {
            get {
                return ResourceManager.GetString("connectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please insert the receiver into the USB port과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string connectionFailedMent {
            get {
                return ResourceManager.GetString("connectionFailedMent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cursor Hide과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string cursorHide {
            get {
                return ResourceManager.GetString("cursorHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pointer Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string cursorSetting {
            get {
                return ResourceManager.GetString("cursorSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap defaultImage {
            get {
                object obj = ResourceManager.GetObject("defaultImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap defaultImage_cyan {
            get {
                object obj = ResourceManager.GetObject("defaultImage_cyan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap defaultImage_red {
            get {
                object obj = ResourceManager.GetObject("defaultImage_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Device Matching과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string deviceMatching {
            get {
                return ResourceManager.GetString("deviceMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Icon DUO {
            get {
                object obj = ResourceManager.GetObject("DUO", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap DUOicon {
            get {
                object obj = ResourceManager.GetObject("DUOicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Icon DUOsaber {
            get {
                object obj = ResourceManager.GetObject("DUOsaber", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap DUOsaberlogo_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("DUOsaberlogo_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Quick mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string enableQuickMode {
            get {
                return ResourceManager.GetString("enableQuickMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Evryone과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string evryone {
            get {
                return ResourceManager.GetString("evryone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   exit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GENERAL MODE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string generalMode {
            get {
                return ResourceManager.GetString("generalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   High과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string high {
            get {
                return ResourceManager.GetString("high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string imageChange {
            get {
                return ResourceManager.GetString("imageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string imagePoointer {
            get {
                return ResourceManager.GetString("imagePoointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap LaftArrow {
            get {
                object obj = ResourceManager.GetObject("LaftArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap LaftArrow1 {
            get {
                object obj = ResourceManager.GetObject("LaftArrow1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Language과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap LArrow {
            get {
                object obj = ResourceManager.GetObject("LArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Low과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string low {
            get {
                return ResourceManager.GetString("low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Magnification과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Magnification {
            get {
                return ResourceManager.GetString("Magnification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Magnifier과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string magnifier {
            get {
                return ResourceManager.GetString("magnifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Magnifier Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string magnifierSetting {
            get {
                return ResourceManager.GetString("magnifierSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Master Only과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string masterOnly {
            get {
                return ResourceManager.GetString("masterOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap min {
            get {
                object obj = ResourceManager.GetObject("min", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Move To Home과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string moveToHome {
            get {
                return ResourceManager.GetString("moveToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   none과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opacity과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Play_arrow {
            get {
                object obj = ResourceManager.GetObject("Play_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Preparing for Device Matching과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string preparingForDeviceMatching {
            get {
                return ResourceManager.GetString("preparingForDeviceMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   master과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string presenter {
            get {
                return ResourceManager.GetString("presenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PTMODE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PTmode {
            get {
                return ResourceManager.GetString("PTmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh Rate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string refreshRate {
            get {
                return ResourceManager.GetString("refreshRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   select as master과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string selectedAsPresenter {
            get {
                return ResourceManager.GetString("selectedAsPresenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preferences과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string settingMain {
            get {
                return ResourceManager.GetString("settingMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   hightlighter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string spotlight {
            get {
                return ResourceManager.GetString("spotlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please check the connection by pressing the button.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SPtext {
            get {
                return ResourceManager.GetString("SPtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Usable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string usable {
            get {
                return ResourceManager.GetString("usable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap xpointerLogo_chois {
            get {
                object obj = ResourceManager.GetObject("xpointerLogo_chois", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap xpointerLogo_chois1 {
            get {
                object obj = ResourceManager.GetObject("xpointerLogo_chois1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
