//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUOsaber.Localization {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Stringlib {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Stringlib() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DUOsaber.Localization.Stringlib", typeof(Stringlib).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   청중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string audience {
            get {
                return ResourceManager.GetString("audience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   발표자 변경과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string changePresenter {
            get {
                return ResourceManager.GetString("changePresenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기기 등록 진행과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string checkForDeviceMatching {
            get {
                return ResourceManager.GetString("checkForDeviceMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프리젠터를 조작하여 연결을 확인하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CMtex3 {
            get {
                return ResourceManager.GetString("CMtex3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   그림에 표시된 버튼을 2초간 눌러주세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CMtext1_1 {
            get {
                return ResourceManager.GetString("CMtext1-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   등록할 준비가 되면 프리젠터의 LED가 반짝입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CMtext1_2 {
            get {
                return ResourceManager.GetString("CMtext1-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   등록이 완료되면 프리젠터의 LED가 깜빡임을 멈춥니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CMtext2_1 {
            get {
                return ResourceManager.GetString("CMtext2-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   깜빡임이 멈춘 것을 확인하면 &apos;다음&apos;을 클릭해주세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CMtext2_2 {
            get {
                return ResourceManager.GetString("CMtext2-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   색상 변경과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string colorChange {
            get {
                return ResourceManager.GetString("colorChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   컬러 포인터과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string colorPointer {
            get {
                return ResourceManager.GetString("colorPointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연결 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string connectionFailed {
            get {
                return ResourceManager.GetString("connectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수신기를 연결해주세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string connectionFailedMent {
            get {
                return ResourceManager.GetString("connectionFailedMent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   신규 기기 등록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string deviceMatching {
            get {
                return ResourceManager.GetString("deviceMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   빠른 포인터 전환과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string enableQuickMode {
            get {
                return ResourceManager.GetString("enableQuickMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   회의 모드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string general_mode {
            get {
                return ResourceManager.GetString("general mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   홈과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미지 변경과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string imageChange {
            get {
                return ResourceManager.GetString("imageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미지 포인터과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string imagePoointer {
            get {
                return ResourceManager.GetString("imagePoointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   배율과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Magnification {
            get {
                return ResourceManager.GetString("Magnification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확대경과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string magnifier {
            get {
                return ResourceManager.GetString("magnifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   홈 화면으로 이동과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string moveToHome {
            get {
                return ResourceManager.GetString("moveToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불투명도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기기 본체 준비과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string preparingForDeviceMatching {
            get {
                return ResourceManager.GetString("preparingForDeviceMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   발표자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string presenter {
            get {
                return ResourceManager.GetString("presenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프레젠테이션 모드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PTmode {
            get {
                return ResourceManager.GetString("PTmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   발표자로 선택과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string selectedAsPresenter {
            get {
                return ResourceManager.GetString("selectedAsPresenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   크기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   하이라이트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string spotlight {
            get {
                return ResourceManager.GetString("spotlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비어있다면 기기를 조작해주세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SPtext {
            get {
                return ResourceManager.GetString("SPtext", resourceCulture);
            }
        }
    }
}
